apiVersion: v1
kind: Service
metadata:
  name: weatherapp-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: weatherapp-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http